# Generated by Django 4.2.17 on 2025-01-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('name', models.CharField(max_length=20)),
                ('assignedTo', models.CharField(max_length=22)),
                ('priority', models.IntegerField()),
            ],
        ),
    ]
