# Generated by Django 4.2.17 on 2025-01-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=29)),
                ('lastname', models.CharField(max_length=39)),
                ('testscore', models.FloatField()),
            ],
        ),
    ]
